### model
model_name_or_path: Qwen/Qwen2-7B-Instruct

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: cmedqa2_train    # 切换成相应语言 med_qa_en_train, cmexam_train, healthcaremagic_train, cmedqa2_train
eval_dataset: cmedqa2_validation  # 切换成相应语言 med_qa_en_validation, cmexam_validation, healthcaremagic_validation, cmedqa2_validation
template: qwen
cutoff_len: 4096
max_samples: 10000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/qwen2-7b/lora/sft/cmedqa2-10k  # 切换成相应语言
logging_steps: 20
save_steps: 10000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
fp16: true
ddp_timeout: 180000000
#resume_from_checkpoint: saves/qwen2-7b/lora/sft/mtl/checkpoint-2800

### eval
#val_size: 0.1
per_device_eval_batch_size: 4
eval_strategy: steps
eval_steps: 10000


#
report_to: none